### ISSUE TITLE
feat: implement 0x31 - BALANCE Opcode

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#117]
Updated with tech strategy:
```[tasklist]
### Tasks
- [x] pop EVM address from stack
- [x] check if EVM address points to a CA or an EOA
- [x] if EOA: convert EVM address to Starknet address
- [x] call native_token -> ERC20.balanceOf(eoa_sn_address)
- [x] return
- [x] if CA: check kakarot_core storage for the balance of the CA
- [x] test it
```

<tr class="bg-indigo-50 dark:bg-black-600"><td colspan="6"><div class="text-sm px-4 md:px-8 py-8 bg-indigo-50 dark:bg-black-600"><table class="table-auto mb-6 bg-indigo-100 dark:bg-black-500 rounded font-medium"><thead><tr class="text-gray-500 uppercase text-xs tracking-wide"><td class="pt-3 px-4">Since</td><td class="pt-3 px-4">Group</td></tr></thead><tbody><tr><td class="pb-3 px-4">Frontier</td><td class="pb-3 px-4">Environmental Information</td></tr></tbody></table><div class="flex flex-col lg:flex-row"><div class="flex-1 lg:pr-8"><p class="leading-5 mb-4"><em>Index 1 is top of the stack. See <a class="underline" href="/#60">PUSH</a>.</em></p><h2 class="text-base font-semibold my-4">Stack input</h2><ol class="list-decimal mb-4"><li class="ml-6"><code>address</code>: 20-byte address of the account to check.</li></ol><h2 class="text-base font-semibold my-4">Stack output</h2><ol class="list-decimal mb-4"><li class="ml-6"><code>balance</code>: balance of the given account in <a class="underline" href="https://www.investopedia.com/terms/w/wei.asp">wei</a>. Returns 0 if the account doesn't exist.</li></ol><h2 class="text-base font-semibold my-4">Example</h2><table class="table-auto mb-4"><thead><tr><th class="py-1 px-2 border-indigo-200 dark:border-black-400 text-gray-800 dark:text-gray-400 text-tiny font-medium break-all"></th><th class="py-1 px-2 border-indigo-200 dark:border-black-400 text-gray-800 dark:text-gray-400 text-tiny font-medium break-all border">Input</th><th class="py-1 px-2 border-indigo-200 dark:border-black-400 text-gray-800 dark:text-gray-400 text-tiny font-medium break-all border">Output</th></tr></thead><tbody><tr><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>1</code></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>0x9bbfed6889322e016e0a02ee459d306fc19545d8</code></td><td class="py-1 px-2 border-indigo-200 dark:border-black-400 text-tiny font-normal break-all border"><code>125985</code></td></tr></tbody></table><p class="leading-5 mb-4"><a class="underline" href="https://www.evm.codes/playground?callValue=125985&amp;unit=Wei&amp;codeType=Mnemonic&amp;code=%27%2F%2F%20Read%20current%20contract%20balance%5CnADDRESS%5CnBALANCE%27_">Reproduce in playground</a>.</p><h2 class="text-base font-semibold my-4">Error cases</h2><p class="leading-5 mb-4">The state changes done by the current context are <a class="underline" href="/?fork=shanghai#FD">reverted</a> in those cases:</p><ul class="list-disc mb-2"><li class="ml-6">Not enough gas.</li><li class="ml-6">Not enough values on the stack.</li></ul><h2 class="text-base font-semibold my-4">Gas</h2><p class="leading-5 mb-4">The static cost is 0. If the accessed address is warm, the dynamic cost is 100. Otherwise the dynamic cost is 2600. See section <a class="underline" href="/about">access sets</a>.</p></div><div class="md:w-96"><div class="flex justify-between items-center"><h2 class="text-base font-semibold my-4">Estimate your gas cost</h2></div><div class="bg-indigo-100 dark:bg-black-500 p-4 rounded shadow"><div><label class="block text-sm text-gray-500 mb-1" for="cold">State: 'address' is cold?</label><div class="mb-4"><label class="mr-3 text-sm"><input type="radio" class="mr-2" value="1">Yes</label><label class="mr-3 text-sm"><input type="radio" class="mr-2" value="0" checked="">No</label></div></div><div class="flex items-center pt-2"><svg class="inline-block fill-current ri text-indigo-500 mr-2" style="width: 16px; height: 16px;"><use xlink:href="#remix_svg__ri-gas-station-fill"></use></svg>Static gas + dynamic gas = 100</div></div></div></div></div></td></tr>

**Comment by lambda-0x** [comment]
id like to implement this (andrelated #156), but if i understand correctly this value is not stored in `ExecutionContext` but it would stored inside EOA contract which is not yet implemented

**Comment by Eikix** [comment]
Here is how I understand the flow of this issue:
- Grab Address from stack
- Convert this EVM-formatted address to Starknet address
- call native token of the chain (erc20 starknet_eth for instance): native_token.balance_of(starknet_address)
- return on the stack the result

Here is how I understand the requirements for this issue:
- We need a way to deterministically map EVM addresses to Starknet address (compute_starknet_address util of main kakarot SC)
- We need to know the native token of the chain (storage variable set in the constructor of the main kakarot SC)

So this issue is blocked until we have the main Kakarot SC logic implemented

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by Eikix** [comment]
Currently blocked by:
- Having the function `compute_starknet_address`
