### ISSUE TITLE
feat: migrate the contract account data structure to kakarot-ssj

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#158]
# Feature Request

In Kakarot Cairo 0, to mimic the EVM contract accounts (Smart Contracts), we use Starknet contracts.
Source: 
- https://github.com/kkrt-labs/kakarot/blob/main/src/kakarot/accounts/contract/library.cairo
- https://github.com/kkrt-labs/kakarot/blob/main/src/kakarot/accounts/contract/contract_account.cairo

Each contract_account needs:
```[tasklist]
### Tasks
- [ ] to store its EVM bytecode (post-constructor EVM Bytecode)
- [ ] have the main kakarot contract as its owner (blocked by kakarot main smart contract being created, but can just create the constructor and logic before hand)
- [ ] be upgradable, by using the new syscall replace_class -> upgrade should be only accessible by either kakarot main SC or a specific role, UpgradeAdministrator (can be a multisig at first)
- [ ] to respect the current API https://github.com/kkrt-labs/kakarot/blob/main/src/kakarot/accounts/contract/contract_account.cairo 
- [ ] the implementation should be thoroughly tested
``` 

Note that for storing its own bytecode we can:
Use storage index: Besides storing 32/16 bytes for each storage, once the hash for the storage location is calculated we can access up to 256 more slots by adding to the index.

Milan made a [cool Alexandria storage list lib for this, we can use it here.](https://github.com/keep-starknet-strange/alexandria/blob/main/src/storage/src/list.cairo)

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by Eikix** [comment]
Linked to #55 and #134 
All three will be closed at the same time

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by Eikix** [comment]
Closing this issue for now as Contract Account will not be an individual Starknet smart contract but rather a storage struct inside KakarotCore
