### ISSUE TITLE
feat: investigate if we can use Herodotus' implementation of RLP in Cairo1 for SSJ

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#159]
# Feature Request

**Describe the Feature Request**

Herodotus has worked on an open source RLP lib in Cairo.
We need RLP encode (and formerly decode) for our validation purposes.

Investigate if the RLP library: https://github.com/HerodotusDev/cairo-lib/blob/main/src/encoding/rlp.cairo
Is usable for us

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/276
- [x] Small audit of RLP lib
- [x] Run tests to check if it works
- [x] If satisfactory, can try to bump it to latest compiler version, or fork it and bump it to latest compiler version
- [x] If satisfactory, can use it as dependency
```

**Describe Preferred Solution**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by danilowhk** [comment]
Right now, Herodotus doesn't support recursive lists as when they were implemented, it wasn't possible to do recursive enums.

https://github.com/HerodotusDev/cairo-lib/blob/dc03294af834519ae5dd965be263446325fafb87/src/encoding/rlp.cairo#L114

Tiago mentioned he would push the updated decode version with recursive lists.

The question about recursive lists came as there are recursive lists testing on EF-test:

https://github.com/ethereum/tests/blob/9b00b68593f5869eb51a6659e1cc983e875e616b/RLPTests/rlptest.json#L136

OBS: These tests are for encoding, but thought of testing decoding witht he same values

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.
