### ISSUE TITLE
dev: create Mermaid diagrams of different scenarios related to the ExecutionContext's run method

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#161]
```[tasklist]
### Tasks
- [ ] Create a `models` folder and inside it, a `execution_context` folder in docs folder
- [ ] Create a valid run diagram
- [ ] Create an errored run diagram
- [ ] Create a revert run diagram
- [ ] Create a stopped run diagram
``` 

Use Mermaid diagrams

**Comment by enitrat** [comment]
@Eikix wouldn't it better as one global flow diagram with conditional branches? 🤔
