### ISSUE TITLE
dev: run gas snapshot compare python script in the CI and comment results in PR

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#163]
```[tasklist]
### Tasks
- [ ] Create a CI job that runs on PR
- [ ] The job runs the compare python script
- [ ] Comments the result on the PR as a report
```

**Comment by ClementWalter** [comment]
see also https://github.com/ClementWalter/madara/blob/8aa5efa51847cdc06ecb0d9585531607689777c2/.github/workflows/benchmarks.yml#L36

https://github.com/benchmark-action/github-action-benchmark/tree/v1/

```
      - name: Compare result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "customBiggerIsBetter"
          output-file-path: ./benchmarking/reports/metrics.json
          alert-threshold: "120%"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-alert: true
          summary-always: ${{ github.ref == 'refs/heads/main' }}
          comment-always: false
          comment-on-alert: false
          auto-push: ${{ github.ref == 'refs/heads/main' }}
```
