### ISSUE TITLE
dev: delete stale bot

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#166]
```[tasklist]
### Tasks
- [x] Delete no-stale and stale labels
- [x] Delete CI action for stale bot
- [x] Delete lock action for stale issues
```

My reasoning is that we're not a huge OSS repo, we have people managing issues on a day to day basis and tracking them.
We don't need this tool to sanitise our repo. As per the wise words of some founder: at first, don't try to scale, do things that don't scale. So we're managing our issues ourselves, no stale bot.
