### ISSUE TITLE
epic: migrate EOA to kakarot-ssj

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#207]
# Feature Request

**Describe the Feature Request**

We want to migrate the smart account EOA to Kakarot SSJ

Reference: 
https://github.com/kkrt-labs/kakarot/blob/0c6e7a62a38e973ad6ceebfbf648841749ffe0ee/src/kakarot/accounts/eoa/externally_owned_account.cairo#L30

**Describe Preferred Solution**

```[tasklist]
### Tasks
- [ ] Look at how the EOA is implemented in Kakarot Cairo Zero
- [ ] Make sure #159 investigation is done 
- [ ] Migrate RLP Library to new Cairo
- [ ] check `supports_interface` best practices for new Cairo and create a sensible interface ID for Kakarot EOA interface
- [ ] implement storage for bytecode check results of #134 to efficiently store bytecode inside storage var of EOA contract (use storage index offset), for now we've decided to use alexandria storage lib from Milan
- [ ] implement EOA `get_evm_address()` method
- [ ] implement EOA `bytecode_len()` method
- [ ] implement EOA __validate__
- [ ] implement EOA __validate_declare__
- [ ] implement EOA __execute__
- [ ] implement constructor logic for EOA (formerly called initialize)
``` 

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.
