### ISSUE TITLE
Migrate RLP Library to new Cairo

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#208]
In Kakarot, the EOA smart account uses RLP encoding

```[tasklist]
### Tasks
- [x] Check if #159 is suitable for RLP encoding, if so, import kkrt-labs/cairo-lib RLP it as a library and close this issue
- [x] If above point is not working, manually migrate RLP (rewrite) and place it in RLP crate in kakarot-ssj
- [x] Implement RLP decoding
- [x] Test RLP decoding and add EF tests for RLP decoding
- [x] Make sure RLP is well tested (migrate cairo zero former tests) and add more if need be (all RLP cases: short and long string, lists, etc.)
```

**Comment by Eikix** [comment]
I think @LucasLvy started but won't have time to finish.
Basically his findings is that RLP from Herodotus is good enough, next task would be to:
- Import RLP from kkrt-labs/cairo-lib fork into kakarot-ssj
- Migrate RLP tests from Kakarot cairo 0 
- Make sure they pass using the RLP from cairo-lib. If it doesn't pass, then alert team and create new issues to either -> fix cairo-lib RLP package, or migrate our own.

**Comment by Eikix** [comment]
> Can take this issue

Assigned you!

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by Eikix** [comment]
@Quentash this is the issue you're doing now and opened a PR for #405

**Comment by Quentash** [comment]
Alright !
