### ISSUE TITLE
check `supports_interface` best practices for new Cairo and create a sensible interface ID for Kakarot EOA interface

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#209]
We currently have: 
In https://github.com/kkrt-labs/kakarot/blob/0c6e7a62a38e973ad6ceebfbf648841749ffe0ee/src/kakarot/accounts/eoa/externally_owned_account.cairo#L105

```
// @dev Return true if the interface_id is supported
// @dev TODO: check what interfaces the contract should support and maybe create one for a kakarot account
// @param interface_id The interface Id to verify if supported
@view
func supports_interface{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}(
    interface_id: felt
) -> (success: felt) {
    if (interface_id == ExternallyOwnedAccount.INTERFACE_ID) {
        return (success=1);
    }
    return (success=0);
}
```

```[tasklist]
### Tasks
- [ ] Check if `supports_interface` is still an interesting and idiomatic method
- [ ] If so, check how ID is officially determined (what is the source EIP? SNIP?), then choose an ID for our EOA smart account
- [ ] Implement supports_interface
```

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by Quentash** [comment]
The SNIP-5 (https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-5.md) is related to this issue.

You can even find the way an id should be calculated in it, the python scripts is given.

So, admitting a kakarot EOA is defined by theses functions :
```
fn supports_interface(felt252) -> bool;
fn is_valid_signature(felt252, Array<felt252>) -> bool;
fn __execute__(Array<Call>) -> Array<Span<felt252>>;
fn __validate__(Array<Call>) -> felt252;
fn __validate_declare__(felt252) -> felt252;
```
The id should be : `0xda6e5bc089be1ce54d429c85fdabf042e660021917106fe636eb4f9c040cca`.

A discussion (https://community.starknet.io/t/starknet-standard-interface-detection/92664/30) can be found discussing the adoption of SRC5 and, 1 month ago, it seemed many projects already adopted this practice.

An example of implementation can be found on the OpenZep ERC721 (https://github.com/OpenZeppelin/cairo-contracts/blob/a1b559c46eaa48d855b049134fd294ce43ee44e7/src/token/erc721/erc721.cairo#L93)

I am available to enlight any confusion.
And if Kakarot adopts this methods, I'd be glad to try to implement it ! :)
