### ISSUE TITLE
feat: implement the test suite for 0x52 - MSTORE opcode

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/kakarot-ssj#247]
```[tasklist]
### Tasks
- [ ] Create the trait for the MSTORE opcode category
- [ ] Create the MSTORE opcode function, write it only as a panic_with_felt252('MSTORE not implement yet')
- [ ] Create the test suite for MSTORE, taking Geth's examples
- [ ] Create the test suite for MSTORE, taking Kakarot cairo0 examples
- [ ] Create the test suite for MSTORE, taking the evm.codes examples
```

**Comment by Quentash** [comment]
Can I have this one please ?

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by khaeljy** [comment]
Resolved in https://github.com/kkrt-labs/kakarot-ssj/pull/290
