### ISSUE TITLE
feat: implement the test suite for 0x53 - MSTORE8 opcode

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/kakarot-ssj#249]
```[tasklist]
### Tasks
- [ ] Create the trait for the MSTORE8 opcode category
- [ ] Create the MSTORE8 opcode function, write it only as a panic_with_felt252('MSTORE8 not implement yet')
- [ ] Create the test suite for MSTORE8, taking Geth's examples
- [ ] Create the test suite for MSTORE8 taking Kakarot cairo0 examples
- [ ] Create the test suite for MSTORE8 taking the evm.codes examples
```

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.
