### ISSUE TITLE
feat: implement the test suite for 0x58 - PC opcode

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/kakarot-ssj#255]
```[tasklist]
### Tasks
- [ ] Create the trait for the PC opcode category
- [ ] Create the PC opcode function, write it only as a panic_with_felt252('PC not implement yet')
- [ ] Create the test suite for PC, taking Geth's examples
- [ ] Create the test suite for PC taking Kakarot cairo0 examples
- [ ] Create the test suite for PC taking the evm.codes examples
```
