### ISSUE TITLE
feat: implement the test suite for 0x59 - MSIZE opcode

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/kakarot-ssj#257]
```[tasklist]
### Tasks
- [ ] Create the trait for the MSIZE opcode category
- [ ] Create the MSIZE opcode function, write it only as a panic_with_felt252('MSIZE not implement yet')
- [ ] Create the test suite for MSIZE, taking Geth's examples
- [ ] Create the test suite for MSIZE taking Kakarot cairo0 examples
- [ ] Create the test suite for MSIZE taking the evm.codes examples
```

**Comment by rkdud007** [comment]
MSIZE don't have specific  Kakarot cairo0 examples(only e2e test), is there specific test suite that you have in mide for MSIZE?

**Comment by enitrat** [comment]
> MSIZE don't have specific Kakarot cairo0 examples(only e2e test), is there specific test suite that you have in mide for MSIZE?

it's a very simple opcode, you can just do two cases with an empty/non-empty memory

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug. Will add this reminder in many places to make sure we keep track of known bugs.

**Comment by enitrat** [comment]
Closed by #286
