### ISSUE TITLE
feat: implement the test suite for 0x50 - POP opcode

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/kakarot-ssj#263]
```[tasklist]
### Tasks
- [ ] Create the trait for the POP opcode category
- [ ] Create the POP opcode function, write it only as a panic_with_felt252('POP not implement yet')
- [ ] Create the test suite for POP, taking Geth's examples
- [ ] Create the test suite for POP taking Kakarot cairo0 examples
- [ ] Create the test suite for POP taking the evm.codes examples
```

**Comment by Quentash** [comment]
Can I have this one please ?
