### ISSUE TITLE
feat: include the bug reports of Kakarot v0 in the development of Kakarot v1

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#324]
The past few months, we've investigated the EVM conformance of [Kakarot v0](https://github.com/kkrt-labs/kakarot). Some issues linked to EVM equivalence are still open on this repo and deserve the utmost attention when developing on Kakarot v1.

We must not reintroduce the same unexpected behaviour in our Cairo rewrite of the EVM.

Here is the list of issues to monitor and keep in mind when developing each opcode and feature for our system:
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot/issues/628
- [ ] https://github.com/kkrt-labs/kakarot/issues/695
- [ ] https://github.com/kkrt-labs/kakarot/issues/678
- [ ] https://github.com/kkrt-labs/kakarot/issues/681
- [ ] https://github.com/kkrt-labs/kakarot/issues/680
- [ ] https://github.com/kkrt-labs/kakarot/issues/689
- [ ] https://github.com/kkrt-labs/kakarot/issues/684
- [ ] https://github.com/kkrt-labs/kakarot/issues/683
- [ ] https://github.com/kkrt-labs/kakarot/issues/691
- [ ] https://github.com/kkrt-labs/kakarot/issues/693
- [ ] https://github.com/kkrt-labs/kakarot/issues/700
- [ ] https://github.com/kkrt-labs/kakarot/issues/688
```

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at this link everytime you take an issue and check your issue isn't targeted by a known bug.

**Comment by Eikix** [comment]
Important update: we are gathering some bugs in the [Kakarot v0 codebase](https://github.com/kkrt-labs/kakarot), we need to make sure each issue and each PR in Kakarot-ssj is aware of the lists of known bugs. Look at [this tracking issue](https://github.com/kkrt-labs/kakarot-ssj/issues/324) everytime you take an issue and check your issue isn't targeted by a known bug.
