### ISSUE TITLE
feat: explore how to run a test using blockifier instead of cairo-test

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#37]
# Feature Request

**Describe the Feature Request**

```[tasklist]
### Tasks
- [ ] look in blockifier codebase how they run tests for cairo 1 files
- [ ] look in starknet_in_rust codebase how they run tests for cairo 1 files
- [ ] try to write a simple cairo 1 file and run some tests using rust native test runner (cargo test) and blockifier 
```

**Comment by enitrat** [comment]
@Eikix Can you add some more details here? What's the purpose of this and, if it yields results, shouldn't it be merged to sn-foundry?

**Comment by Eikix** [comment]
This issue was initially created to explore how hard it'd be to not use SN foundry and run our tests with blockifier and was initially attributed to @ftupas, but seeing that SN foundry evolves fast, it was de-prioritized, closing for now as we'll most likely use snfoundry
