### ISSUE TITLE
epic: implement the CALL opcodes: CALL, STATICCALL, DELEGATECALL, CALLCODE

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#390]
## Feature Request

Implement the CALL opcodes: CALL, STATICCALL, DELEGATECALL, CALLCODE

### Describe the Feature Request

Now that we have a working machine design, let's implement CALL, STATICCALL, DELEGATECALL and CALLCODE

### Describe Preferred Solution
Draw inspiration from:
https://github.com/ethereum/execution-specs/blob/8b8c7c1a7437510f614272392275855de26209d3/src/ethereum/berlin/vm/instructions/system.py#L309

If possible, implement a `generic_call` util that'll be used by all CALL opcodes.

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/391
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/392
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/393
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/394
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/395
``` 

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No
