### ISSUE TITLE
feat: create the KakarotCore smart contract 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#398]
## Feature Request

- create the KakarotCore smart contract 

### Describe the Feature Request

To move forward with many features, we refer to the KakarotCore smart contract, cornerstone of our architecture.

### Describe Preferred Solution

```[tasklist]
### Tasks
- [x] Create the KakarotCore smart contract
- [x] It should be ownable using OZ ownable
- [x] It should be upgradeable (using `replace_class_syscall`)
- [x] It should have the same API as the Kakarot SC in Cairo0, except for the `blockhash registry` methods (deprecated for now)
- [x] Each function in the Kakarot API can remain a TODO for now (e.g. `eth_send_transaction`, `eth_call`, `compute_starknet_address`). Note that in cairo0 we separate library from contract, this is no longer needed.
- [x] Define all the storage in the Storage struct: native_fee, owner, and LegacyMap<evm_address, KakarotContractStorage>
```

### Related Code

References:
- https://github.com/kkrt-labs/kakarot/blob/e94997389b0b741ef8989c32b427cfa933a3aaee/src/kakarot/library.cairo#L1
- https://github.com/kkrt-labs/kakarot/blob/e94997389b0b741ef8989c32b427cfa933a3aaee/src/kakarot/kakarot.cairo#L3

### Additional Context

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No

Referenced here:
https://github.com/kkrt-labs/kakarot-ssj/issues/397
