### ISSUE TITLE
feat: add Ownable to Kakarot Core smart contract, if possible using Components and OZ Ownable

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#400]
### Describe the Feature Request

Let's add an owner to the Kakarot Core smart contract for critical operations!

```[tasklist]
### Tasks
- [ ] If possible, implement Ownable using components, if not possible, import Ownable from OZ cairo contracts.
- [ ] Set owner in the constructor of Kakarot Core
- [ ] Implement a getter for the owner of Kakarot Core
- [ ] Implement a transferOwnership method
- [ ] Test the feature
``` 

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by khaeljy** [comment]
Can I get this one pls?

**Comment by enitrat** [comment]
@khaeljy i will to take this one
