### ISSUE TITLE
dev: create two new error enums: VM error and InternalError

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#402]
```[tasklist]
### Tasks
- [ ] Create the StarknetError enum and refactor all Starknet specific errors inside it
- [ ] Create the VMError enum and it should be an enum of sub error types: EVMError and StarknetError
- [ ] Refactor opcodes return signature to return a VMError instead of an EVMError
```

**Comment by enitrat** [comment]
are `TypeConversionError` and else StarknetError? If yes the name doesn't seem very adapted to me. I'd prefer something more generic, like `InternalError`

**Comment by Eikix** [comment]
Ahh could be StarknetError for syscalls, 
TypeConversionError should be something else I agree

**Comment by enitrat** [comment]
enumception

**Comment by azurwastaken** [comment]
Hello !
are you working on it @Eikix or can i do it ?

**Comment by Eikix** [comment]
> Hello !
> 
> are you working on it @Eikix or can i do it ?

Hey:), thanks for your swift response, after discussing with @enitrat, we're waiting a bit to implement this feature to see if it makes sense in our current architecture,

For now let's keep using EVMError everywhere as a global error type for our repository

**Comment by azurwastaken** [comment]
> > Hello !
> > are you working on it @Eikix or can i do it ?
> 
> Hey:), thanks for your swift response, after discussing with @enitrat, we're waiting a bit to implement this feature to see if it makes sense in our current architecture,
> 
> For now let's keep using EVMError everywhere as a global error type for our repository

Oh ok I see !
I was working on a solution yesterday that would have allowed to have more specified errors type and also allowed to had type of errors without breaking any existing code. So if you change your mind feel free to assign me to this task :)

**Comment by Eikix** [comment]
> > > Hello !
> 
> > > are you working on it @Eikix or can i do it ?
> 
> > 
> 
> > Hey:), thanks for your swift response, after discussing with @enitrat, we're waiting a bit to implement this feature to see if it makes sense in our current architecture,
> 
> > 
> 
> > For now let's keep using EVMError everywhere as a global error type for our repository
> 
> 
> 
> Oh ok I see !
> 
> I was working on a solution yesterday that would have allowed to have more specified errors type and also allowed to had type of errors without breaking any existing code. So if you change your mind feel free to assign me to this task :)
> 
> 

I'm open to seeing your design proposal, feel free to open a draft pr and we can discuss it

**Comment by Eikix** [comment]
> > > Hello !
> 
> > > are you working on it @Eikix or can i do it ?
> 
> > 
> 
> > Hey:), thanks for your swift response, after discussing with @enitrat, we're waiting a bit to implement this feature to see if it makes sense in our current architecture,
> 
> > 
> 
> > For now let's keep using EVMError everywhere as a global error type for our repository
> 
> 
> 
> Oh ok I see !
> 
> I was working on a solution yesterday that would have allowed to have more specified errors type and also allowed to had type of errors without breaking any existing code. So if you change your mind feel free to assign me to this task :)
> 
> 

I'm open to seeing your design proposal, feel free to open a draft pr and we can discuss it

**Comment by azurwastaken** [comment]
Here it is :)
