### ISSUE TITLE
dev: make Exponentiation in math.cairo completely generic

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#408]
```[tasklist]
### Tasks
- [ ] refactor Exponentiation (not WrappingExponentiation) to have trait bounds on T, T should implement addition, multiplication and all the traits necessary to perform exponentiation. Can take reference in [Herodotus' cairo-lib](https://github.com/HerodotusDev/cairo-lib/blob/main/src/utils/math.cairo)
- [ ] then remove implementations of Exponentiation for u256 and u128 
- [ ] everything should still work, tests should pass
```

**Comment by akhercha** [comment]
Hi, happy to try this one!
