### ISSUE TITLE
feat: integrate ef-tests into ssj CI

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-ssj#414]
## Feature Request
Integrate the current [ef-tests runner](https://github.com/kkrt-labs/ef-tests/tree/main) into the ssj CI, allowing for progressive inclusion of the EF tests.

## Minimal required parts in ssj

```[tasklist]
### Tasks
- [x] Expose an `eth_call` entrypoint such as available in [V0](https://github.com/kkrt-labs/kakarot/blob/main/src/kakarot/library.cairo#L339). We can skip the create branch for now.
- [x] Implement [EVMInstructions.run()](https://github.com/kkrt-labs/kakarot/blob/main/src/kakarot/instructions.cairo#L601)
- [x] Implement [decode_and_execute()](https://github.com/kkrt-labs/kakarot/blob/main/src/kakarot/instructions.cairo#L48)
- [x] Implement minimal [call](https://github.com/kkrt-labs/kakarot/blob/main/src/kakarot/instructions/system_operations.cairo#L234) opcode, which includes initializing and finalizing a subcontext. Care must be taken to avoid [mistakes made on V0 implementation](https://github.com/kkrt-labs/kakarot/issues/718).
- [x] Implement basic contract account, for now logic can be the same as [V0](https://github.com/kkrt-labs/kakarot/blob/main/src/kakarot/accounts/contract/library.cairo#L43)
```

**Comment by Eikix** [comment]
As for contract account, we decided that they wouldn't be individual starknet smart contract, and have started to go this way, we can't go like v0 on this afaik

Do we need a minimal EOA?

**Comment by Eikix** [comment]
> I mean we can use a normal argent EOA if there is no EOA available yet

Does it work the way we want?
-> even if we skip approval, the part where there is RLP::decode, and calling kakarot main contract?

**Comment by greged93** [comment]
I mean you could just call Kakarot no? I think the way we check this doesn't happen in Kkrt is that we check that the caller matches the eoa class hash we deployed kakarot with in the constructor. If I just deploy with a regular argent account class hash it should be fine.

**Comment by greged93** [comment]
All the above items have been added and the ef-tests can now be integrated in the CI
