### ISSUE TITLE
feat: deploy contract account

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#422]
## Feature Request
Create the deploy contract account flow.

 The bytecode of the contract deployed

## Minimal required parts in ssj

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/424
- [ ] Call the `run` function with a machine initialized with the deploy transaction bytecode
- [ ] Use the return data of the run as the bytecode of the contract
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/423
```
