### ISSUE TITLE
meta-epic: plan the migration and create corresponding issues + spec the issues

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#44]
# Feature Request

I have looked a bit into ssj, there still needs to be a lot (almost all) of issues created and spec’d
Namely: 
```[tasklist]
### Tasks
- [x] a general flow of migration should be created on notion (public page, or as a contributing -> migration.md -> look at kakarot cairo 0 codebase, assess what is good to be directly “translated” (how to do it? Trait? impl? struct? which types? uint?), and assess what can be changed slightly to be better (e.g. execution context) != over optimizing in advance, then creating unit testing and then creating integration testing (snfoundry is bugged for now, awaiting cairo 2.1.0)
- [x] how we port over all of our data structures (execution context, but all of them, really)
- [x] how we port our utils
- [ ] how we port our precompiles (cairo1 rewrite? libfuncs? letting SW handle it, e.g. for sha256)
- [ ] many opcodes still need to be spec’d and created
```
