### ISSUE TITLE
feat: implement CREATE2 opcode

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#455]
Implement the CREATE opcode.

Check:
- KKT0 
- Current PR @ClementWalter from Clement to refactor the state in KKT0
- EELS: execution-specs https://github.com/ethereum/execution-specs/tree/master/src/ethereum/shanghai/vm
- edge cases

```[tasklist]
### Tasks
- [ ] Implement CREATE2 opcode
- [ ] Don't forget to increase the CA nonce for each CREATE2 invocation. Note that a PR from @enitrat will soon abstract the nonce storage changes in a Journal, or LocalStorage struct. CREATE can wait until then.
- [ ] Test that the correct address was computed using an example.
- [ ] test that the constructor is executed.
- [ ] check that the nonce of the creator is incremented.
- [ ] check that the nonce of the created account is set to 1
- [ ] check that in case of failure, 0 is returned to the stack and no state is changed
- [ ] check that in case of success, the address of the newly created account is returned to the stack
```

**Comment by Eikix** [comment]
Help https://github.com/ethereum/execution-specs/blob/master/src/ethereum/shanghai/utils/address.py
