### ISSUE TITLE
feat: EOAs should store chain_id as an immutable storage variable 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#475]
### Describe the Feature Request

During validate function, EOAs have to check that the chain id provided inside the transaction is valid. How? By checking it matches the current chains'.
Since chain_id is now a KakarotCore storage var, we'd ideally need to call KakarotCore::chain_id() inside validate.

Because of:
```
from what I understand: no

https://docs.starknet.io/documentation/architecture_and_concepts/Accounts/validate_and_execute/

> Currently, Starknet enforces that validate does not call external contracts.
```

### Describe Preferred Solution

```[tasklist]
### Tasks
- [ ] Delete the constructor function of EOA, as it is dead code. It is never used. Rather `EOATrait::deploy` deploys the UnitializedAccount and specializes it into an EOA. 
- [ ] Add a `chain_id` storage variable in EOA storage struct
- [ ] Add a getter and a setter for chain_id, add a permission for setting the `chain_id` to be only callable by Kakarot (just check caller == self.kakarot_core_address.read())
- [ ] Add in EOA::deploy a step to call the setter for chain_id
- [ ] Update tests, documentation and formatting
- [ ] Note that deploy_eoa method will have to be modified accordingly in test_utils, as now it has to run through the new flow: 1. deploy UnitializedAccount, then run initialize/upgrade on it, and then setting the chain_id. Can draw inspiration in #486 
``` 

At deployment of EOA, call KakarotCore::chain_id() and store it locally. It's inefficient but there is no better solution.

### Additional Context

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No

**Comment by chachaleo** [comment]
Can I take this issue ?

**Comment by Eikix** [comment]
> Can I take this issue ?

Sure! Let us know if you need help
