### ISSUE TITLE
refactor: make each CA in Kakarot SSJ a unique Starknet Smart Contract

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#481]
Refactor:

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/482
- [x] Modify contract_account.cairo to call a SN contract rather than KakarotCore storage
- [x] Modify deploy
- [x] Modify nonce
- [x] Modify bytecode
- [ ] #477
- [x] Test the new behaviour
```
