### ISSUE TITLE
dev: move EOA modules from EOA crate inside `contracts` crate as a module

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#485]
```[tasklist]
### Tasks
- [ ] Create an eoa folder in the crate `contracts`, inside `src`
- [ ] Move all code from eoa crate to this newly created folder
- [ ] Fix imports
- [ ] Delete the EOA crate
- [ ] Delete dependencies to the EOA crate in all other crates of the workspace
- [ ] Fix tests
- [ ] Fix imports again^^
- [ ] Don't forget to scarb format
```

**Comment by Quentash** [comment]
Want me to take care of this ?

**Comment by Eikix** [comment]
> Want me to take care of this ?

Great, yes please
