### ISSUE TITLE
dev: create a StarknetJS script to generate on the fly SN addresses for test_kakarot_core_compute_starknet_address() in crates/contracts/src/tests/test_kakarot_core.cairo

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#487]
Reference to https://github.com/kkrt-labs/kakarot-ssj/pull/483#discussion_r1376517901

```[tasklist]
### Tasks
- [ ] add starknet js to kakarot ssj repository (using bun)
- [ ] inside a scripts folder, create a compute_starknet_address.ts file
- [ ] create documentation in readme
- [ ] add a documentation reference to this script in crates/contracts/src/tests/test_kakarot_core.cairo>test_kakarot_core_compute_starknet_address
``` 

Code snippet for inspiration:

```typescript
import { CallData, hash } from 'starknet';

// the class hash of the contract to be deployed
const classHash =
  0x23e3d667a815a28526089de7cdd8926696a24e272805343dc35a8a3b5e5d4ban;

// Salt is the EVM address of the contract to be deployed
const salt = 0x65766d5f61646472657373n;

// The Kakarot Address when deploying Kakarot first in a Scarb test environment 
const kakarotAddress = 1n;

const CONSTRUCTOR_CALLDATA = [kakarotAddress, salt];

console.log(CONSTRUCTOR_CALLDATA);

function guessAddress() {
  return hash.calculateContractAddressFromHash(
    salt,
    classHash,
    CONSTRUCTOR_CALLDATA,
    1n
  );
}

console.log(guessAddress());

```

**Comment by chachaleo** [comment]
Can I take this to prepare for : Issue #475 ?

**Comment by Eikix** [comment]
> Can I take this to prepare for : Issue #475 ?

Fine for me!
