### ISSUE TITLE
feat: eth_send_transaction

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#556]
eth_send_transaction endpoint:

```[tasklist]
### Tasks
- [ ] create eth_send_transaction endpoint
- [ ] reproduce kkt0 logic
- [ ] use handle_call
- [ ] can only be called by EOA for now
```

**Comment by greged93** [comment]
closed by #560
