### ISSUE TITLE
epic: create spec compliant gas accounting

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#582]
### Describe the Feature Request
 
```[tasklist]
### Tasks
- [ ] add per opcode static gas accounting
- [ ] add intrinsic gas costs
- [ ] add memory extension costs
- [ ] add access list (warm/cold) address gast costs
- [ ] add eth transfer gas costs
```
