### ISSUE TITLE
add per opcode static gas accounting

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#583]
```[tasklist]
### Tasks
- [ ] Add a gas_used field in the execution context, it is initialized to 0
- [ ] Add a per opcode gas cost according to the spec
- [ ] Add a check before each opcode logic that the gas_used + opcode gas < gas_limit
- [ ] Test the feature: test that gas is increased when an opcode is ran
```

**Comment by bajpai244** [comment]
@Eikix , I can take this 🙌
