### ISSUE TITLE
add intrinsic gas costs

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#584]
Intrinsic Gas: Each transaction has an intrinsic cost of 21000 gas. Creating a contract costs 32000 gas, on top of the transaction cost. Again: calldata costs 4 gas per byte equal to 0, and 16 gas for the others (64 before the hardfork Istanbul). This cost is paid from the transaction before any opcode or transfer execution.

source: evm.codes

Reference for the issue:
https://github.com/ethereum/execution-specs/blob/master/src/ethereum/shanghai/fork.py#L689
https://github.com/ethereum/execution-specs/blob/master/src/ethereum/shanghai/fork_types.py

```[tasklist]
### Tasks
- [ ] Create intrinsic gas cost constants for a tx, 21k for tx, and, 
- [ ] 32k additional gas for creating a contract 
- [ ] Calldata costs: 4 gas per byte equal to 0, 16 gas for the others
```

**Comment by akhercha** [comment]
Hey, happy to try this one! The goal is to create a function equivalent to `calculate_intrinsic_cost`, right? Do we have a prefered location in the code for such a function?

**Comment by Eikix** [comment]
Let's just wait a bit till we merge the static gas PR and finish the strategy on gas, 
Then LFG:)

**Comment by enitrat** [comment]
@akhercha good now

**Comment by enitrat** [comment]
@akhercha don't handle AccessListTransactions for now

**Comment by enitrat** [comment]
@akhercha could you do this by monday / tuesday?

**Comment by akhercha** [comment]
Sure, I'll start asap!
