### ISSUE TITLE
add access list (warm/cold) address gast costs

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#586]
Access Sets
Access sets are defined per external transaction, and not per call. Each transaction may be defined by some combination of its sender, calldata, or callee. Transactions can either be external or internal. External transactions are sent to the Ethereum network. Internal transactions are triggered by external transactions that have executed the xCALL instruction. As such, internal transactions are also known as calls. Access sets can be thought of as two independent types of lists: those of touched addresses, and those of touched contract storage slots.

When an address is accessed by a transaction, instruction, or used as caller or callee, it is put in the access set. Calling the opcode [BALANCE](https://www.evm.codes/#31), on an address not present in an access set costs more than if the address were already in the set. Other opcodes that can modify the access set include [EXTCODESIZE](https://www.evm.codes/#3B), [EXTCODECOPY](https://www.evm.codes/#3C), [EXTCODEHASH](https://www.evm.codes/#3F), [CALL](https://www.evm.codes/#F1), [CALLCODE](https://www.evm.codes/#F2), [DELEGATECALL](https://www.evm.codes/#F4), [STATICCALL](https://www.evm.codes/#FA), [CREATE](https://www.evm.codes/#F0), [CREATE2](https://www.evm.codes/#F5) and [SELFDESTRUCT](https://www.evm.codes/#FF). Each opcode has their own cost when modifying the access set.

Touch slot lists are a set of storage slot keys accessed by contract addresses. Slot lists are initialized to empty. When an opcode accesses a slot that is not present in the set, it adds it to it. Opcodes that can modify the touched slot list are [SLOAD](https://www.evm.codes/#54) and [SSTORE](https://www.evm.codes/#55). Again, both opcodes have their own cost when modifying the access set.

If a context is reverted, sets are reverted to their state before the context.

If an address or storage slot is present in the set, it is called 'warm'; otherwise it is 'cold'. Storage slots that are touched for the first time in a transaction change from cold to warm for the duration of the transaction. Transactions can pre-specify contracts as warm using EIP-2930 access lists. The dynamic cost of some opcodes depend on whether an address or slot is warm or cold. After the hardforkBerlin, all precompiled contract addresses are always ‘warm’.
```[tasklist]
### Tasks
- [x] add a way to know if a fetch on an account is hot or cold according to the specs of access lists
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/617
- [x] add access set gas costs and implement them - e.g. opcode BALANCE, on an address not present in an access set costs more than if the address were already in the set. Other opcodes that can modify the access set include EXTCODESIZE, EXTCODECOPY, EXTCODEHASH, CALL, CALLCODE, DELEGATECALL, STATICCALL, CREATE, CREATE2 and SELFDESTRUCT.
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/616
```
