### ISSUE TITLE
refactor: The Great Refactor - Switch VM design from flat sequential execution of contexts to "instant resolve of contexts"

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#598]
## Feature Request

Currently, we're flattening every sub-context we meet, like Nethermind and Kakarot Cairo 0:
- Only one instance of the interpreter runs until the final Pc is reached
- When a new sub context is created, we simply set Pc back to 0, and point the `Machine` to the newly created sub context, and run the Pc until end on the newly loaded Bytecode.
- When Pc(sub-context) runs out, we restore Pc(parent-context), Bytecode(parent-context) and continue the run 
- A good mental model for this is a long straight line, no "nested" or "recursed" calls, just inlining of executions

This has led us to several blockers due to the Cairo v2 compiler.
1. Sub-context hold a reference to their parent, as Nullable<T>, a Cairo smart pointer. We are not able due to a compiler bug to hold a FeltDict252 for a T inside Nullable<T>
2. State changes dicts can't live inside T inside Nullable<T>

### Describe the Feature Request

We'll change our implementation to switch to the design of [EELS](https://github.com/ethereum/execution-specs/tree/master/src/ethereum/shanghai/vm), Geth, Reth and other EVM implementations:
- As your ran advances, any time you reach a new sub-context, instantly run it until pc ends. Then, continue the execution of the parent.
- What this creates is potentially a lot of nested function calls
- But thankfully, we need not keep track of parents to "jump" back to the parent context after finishing executing a child ctx as we were doing. 

### Describe Preferred Solution

```[tasklist]
### Refactor types
- [x] Add a Stack and Memory field to Execution Context (move them from Machine)
- [x] Delete the Parent context field in Execution Context
- [x] Add a State field in Execution context of type State (move it from Machine)
- [x] Add a depth field in Execution Context
```

```[tasklist]
### Tasks
- [x] Change the signature of `Interpreter::decode_and_execute` to take an execution context and return a Result<(),EVMError>
- [x] Change the signature of `Interpreter::run` to take an execution context as input, and return a RunSummary, or better said, a struct that contains all the information necessary for the run to "resolve" -> return_data, status... you may heavily depend on process_message, [process_message_call](https://github.com/ethereum/execution specs/blob/master/src/ethereum/shanghai/vm/interpreter.py#L87), process_create_message
- [ ] Whenever we enter a sub-context, i.e. we encounter a call or create family opcode, we pass the ExecutionContext State property down to the child, at the beginning of its execution, the child will take a deep_copy or snapshot of the State, will run, if it is successful, it'll return the updated State, if not, it'll rollback and return the unchanged State.
- [ ] The state structure will change: we no longer need contextual and transaction changes, we simply have a Statelog of changes, and ability to rollback to former versions of the State
```

```[tasklist]
### Cleanup
- [ ] Delete the EVMInterpreter struct
- [ ] Delete the Machine struct
- [ ] Delete the Machine file, trait and tests
``` 

### Additional Context

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No
