### ISSUE TITLE
epic: test evm conformance with ethereum general state transition tests 

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/kakarot-ssj#61]
# Feature Request

**Describe the Feature Request**

General State Tests are tests created by the ethereum foundation to test transaction handling.

The general structure is:

- Given 
   - an [env](https://github.com/ethereum/tests/blob/develop/GeneralStateTests/VMTests/vmArithmeticTest/add.json#L20), 
   - [account state](https://github.com/ethereum/tests/blob/develop/GeneralStateTests/VMTests/vmArithmeticTest/add.json#L292), and a transaction
- When
   - executing a [transaction](https://github.com/ethereum/tests/blob/develop/GeneralStateTests/VMTests/vmArithmeticTest/add.json#L343)
- Then
   - the ethereum tests expects a certain [result](https://github.com/ethereum/tests/blob/develop/GeneralStateTests/VMTests/vmArithmeticTest/add.json#L187)

We should focus on using the structure of these tests, specifically for the Merge fork, to establish adequate transaction handling of our evm implementation.

**Describe Preferred Solution**

There are two distinct formats of GeneralStateTests that can be somewhat confusing:

General State Tests Format: This format is well-documented [here](https://ethereum-tests.readthedocs.io/en/latest/test_types/gstate_tests.html) and primarily focuses on the specifics of the state transition for Ethereum transactions.

Blockchain Tests Format: Within the blockchain tests folder structure, there's a sub-folder named /BlockchainTests/GeneralStateTests. This essentially contains a copy of the General State Tests. However, instead of just focusing on the state transition, it runs the tests within the broader context of blockchain logic. The same tests in a different format is explicitly mentioned [here](https://ethereum-tests.readthedocs.io/en/v6.0.0-beta.1/test_types/blockchain_tests.html), but here in the [latest docs](https://ethereum-tests.readthedocs.io/en/latest/test_types/blockchain_tests.html).

For our purposes, we'll be utilizing both formats of GeneralStateTests. Why? The Blockchain Test format offers a more detailed [post-state](https://github.com/ethereum/tests/blob/develop/BlockchainTests/GeneralStateTests/VMTests/vmArithmeticTest/add.json#L626). By combining this with the GeneralStateTest format, we can concentrate on the state transition of transactions without the overhead of mimicking how ethereum manages state (via a merkle tree). This approach provides a streamlined method to assert post-state transitions.

In rust-like pseudocode, the general shape of test running would look like

```rust
let general_state_tests = directory("tests/GeneralStateTests/").filterJSONFiles();

for (general_state_test, general_state_test_filename) in general_state_tests {
  // focus on the Merge fork
    let sub_tests = general_state_test.post["Merge"];
    for (sub_test, sub_test_idx) in sub_tests {
        // fresh kakarot state is fresh starknet state, with the kakarot system deployed on top
        let prepared_kakarot_state = fresh_kakarot_state();
        // the transaction in a general state test has arrays for data, value, and gas for each transaction. the post state defines concrete indexes for the expected results 
        let concrete_transaction = general_state_test.transaction(sub_test.indexes.data, sub_test.indexes.value, sub_test.indexes.gas);
        // eth->starknet types here
        let kakarot_env = general_state_test.env.into();
        let kakarot_transaction = concrete_transaction.into();
        // initialize test's desired pre state
        for (address, state) in general_state_test.pre {
            prepared_kakarot_state.write(address, state);
            
            }

        // assuming we define a unique entry point for the general state tests, like we have for the `test_cases` for bytecode strings                  
        let (return_data: felt*, updated_kakarot_state, events) = await kakarot_system.general_state_test_entry_point(prepared_kakarot_state, kakarot_env, kakarot_transaction);

   // here load a unique file generated from a conformant evm (i.e. geth) to get the post state we check against
        
   let post_state_check = subtest.post;
   // we assert that the geth-evaluated trace matches our post state     
   assert_conformance!(updated_kakarot_state, post_state_check);

    let eth_logs = event.into();
    // need to convert starknet log data to ethereum logs and rlp encode and keccak hash the logs to assert equality
    // see: https://github.com/ethereum/go-ethereum/blob/master/tests/state_test_util.go#L207
    let hashed_rlp_logs = encode_and_hash_log(eth_logs);
    assert_eq!(hashed_rlp_logs, sub_test.logs);
        

  
    }
}
```

```[tasklist]
### Tasks
- [ ] include ethereum tests as a submodule
- [ ] create prescript that merges the necessary fields across the two formats of GeneralStateTest and handles eth->starknet type conversions
- [ ] implement block_information opcodes with in a way that is parametrizable by the env field of a GeneralStateTest
- [ ] create necessary entry point for GeneralStateTests
- [ ] https://github.com/kkrt-labs/kakarot-ssj/issues/67
``` 

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [ ] Yes
- [ ] No
