### ISSUE TITLE
feat: make `chain_id` an environmental variable (injected by Starknet in the Environment data structure at transaction time)

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#641]
### Describe the Feature Request

```[tasklist]
### Tasks
- [ ] Refactor `chain_id` variable to come from syscall (backend object) at the beginning of a call to Kakarot, into the Environment object. Check with ef-tests team that this is okay for them in terms of updates
- [ ] Refactor tests
- [ ] Refactor CHAINID opcode to grab the chainid from the environment
- [ ] Refactor the EOA to not rely on a storage slot to have the chain_id but rather calls it from syscall 
```

**Comment by bajpai244** [comment]
@Eikix , if I get this right, u are suggesting to share the same chain_id as the starknet chain? And if yes, what are the some advantages of this?

**Comment by Eikix** [comment]
> @Eikix , if I get this right, u are suggesting to share the same chain_id as the starknet chain? And if yes, what are the some advantages of this?

Yes, we completely control this since we run a Madara or Starknet instance. And since Kakarot will not be deployed onto Starknet for the foreseeable future, this is sounder.
1. advantage: no need to set it an the storage slot level
2. it's part of the environment information, it'll lighten the code of EOA and Kakarot to have the chain_id be injected by the "backend" in @ClementWalter's words -> the environment info

**Comment by TAdev0** [comment]
@Eikix  may i be assigne to this issue?
