### ISSUE TITLE
dev: investigate websocket capabilities for Kakarot RPC

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#697]
```[tasklist]
### Tasks
- [ ] investigate if jsonrpsee can support web sockets
- [ ] investigate which evm routes are needed for block scout
- [ ] investigate the most used evm routes for ws by devs
- [ ] classify them by priority level
- [ ] propose first implementation of ws on kakarot rpc
```
