### ISSUE TITLE
dev: remove deploy_fee storage var

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-ssj#729]
We no longer use deploy_fee for now

```[tasklist]
### Tasks
- [ ] in kakarot core, delete deploy_fee
- [ ] delete getter for deploy fee
- [ ] all mentions of deploy_fee
```

**Comment by TAdev0** [comment]
@Eikix  may i be assigned to this one?
