### ISSUE TITLE
epic: benchmark different parts of the codebase

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-ssj#849]
In an effort to highlight parts that could be optimized by the compiler, produce several benchmarks of core components and functions of the Kakarot implementation, and compare them to their CairoZero counterpart.

Profiling can be done using the [`cairo-profiler`](https://github.com/software-mansion/cairo-profiler)

## Data Structures
- [ ] Profile the Stack
- [ ] Profile the Memory

## Utils
- [ ] Profile conversion from and to bytes

Needs more scoping.

**Comment by enitrat** [comment]
duplicate
